version: '3'
services:
  shiza_app:
    image: node:20
    container_name: shiza_web
    working_dir: /app
    volumes:
      - /app/node_modules
    command: bash -c "git clone https://github.com/megaarcv/Tes.git . && npm install && node server.js"
    ports:
      - "80:3000"
    restart: always
